FROM odoo:latest

RUN chmod -R 777 ./mnt/extra-addons

COPY /custom_addons_staging /mnt/extra-addons

RUN chmod -R 777 ./etc/odoo/odoo.conf

COPY /config/odoo_staging.conf /etc/odoo/odoo.conf

CMD ["odoo", "-c", "/etc/odoo/odoo.conf"]